### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#278]
# Sprint 5

Sprint 5 will be focused on improving the user and contributor experience for FOSSA CLI. The ideal we're working towards is a zero-assistance deployment on 95% of non-enterprise projects and 80% of enterprise projects.

Our target date for delivering sprint 5 is October 5th, 2018.

## Tasks

Tasks are tracked in the [Sprint 5 project](https://github.com/fossas/fossa-cli/projects/15).

### Enable users to configure the CLI without help

- [ ] Document module configuration @liftM 
- [ ] Document analysis strategies @liftM 
- [ ] Document common integrations @liftM 
- [ ] Document build system behaviour @liftM 

### Enable users to debug CLI error messages without help

- [ ] Add error message SLA to README: bad error messages should be considered bugs @liftM 
- [ ] Design, implement, and migrate to `package errors` for ergonomic application-level error reporting
	- [x] Design initial `package errors` handling prototype @liftM 

### Improve ease of integration

- [ ] Add automatic fallback strategies to analysers
	- [x] Node.JS fallbacks @microsoftly 
	- [x] Ruby fallbacks
	- [ ] Python fallbacks
	- [ ] Maven fallbacks

### Scale the engineering team

- [ ] Write contributor documentation
	- [ ] Make existing documentation public
	- [ ] Document build systems
	- [ ] Revise Go setup documentation
- [ ] Develop and experiment with new project planning methods
- [ ] Improve the contributor experience for non-FOSSA engineers
	- [x] Fix CI for fork PRs
	- [ ] Provide public documentation for development and testing workflow
	- [x] Reduce weight of development Docker images @liftM 
- [x] Improve testing and CI feedback
	- [x] Refactor CI and integration testing design @microsoftly @liftM 
	- [ ] Migrate existing shell tests to native `*_test.go` tests @microsoftly 

## Team

- @liftM
- @microsoftly 
- @zlav
