### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#30]
We've got a good framework for manual integration testing, but there's a lot of room for improvements here:

- [x] Run integration tests automatically in CI.
- [ ] Set up golden files in integration tests and CI so that we know when output changes occur.
- [x] Refactor effecting code to take a service-provided implementation (in preparation for unit tests).
- [x] Add automatic unit tests (for pure logic such as parsing).

**Comment by ilikebits** [comment]
Closing to reduce noise. Will reopen individual action items.
