### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#31]
Error messages are currently geared towards being clear for CLI developers, not end users. The general theme is that some very general failure modes (e.g. bad server response code) usually occur for very specific reasons (e.g. user forgot to upload this revision). Here are some improvements:

- [ ] Better error message for a locator that isn't found (usually due to bad locator configuration or VCS inference)
- [ ] Better error message for invalid API key is invalid during `fossa test`
- [ ] Running `fossa test` on a non-existent revision only responds with 500
- [ ] Distinguish between "user has not uploaded provided build" and "FOSSA has not yet applied the provided build" during `fossa test`

**Comment by ilikebits** [comment]
Closing in favor of #184.
