### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by liftM** [fossas/fossa-cli#335]
This is a collection of issues that were out of scope at the time and/or closed to reduce noise, but may be added back to our roadmap at some point.

Issues are collected here to reduce noise.

### Gradle
- [ ] [Gradle `Build()`](https://github.com/fossas/fossa-cli/issues/79)

### NuGet
- [ ] [Filter out system dependencies](https://github.com/fossas/fossa-cli/issues/123)

### PHP
- [ ] [Parse `vendor/**/component.json`](https://github.com/fossas/fossa-cli/issues/50)

## Refactors
- [ ] [Streaming `exec.Run`](https://github.com/fossas/fossa-cli/issues/14)

## CI
- [x] [Automatic releases within CI](https://github.com/fossas/fossa-cli/issues/220)

## Documentation
- [ ] [Add GIFs to README](https://github.com/fossas/fossa-cli/issues/57)
- [ ] [Add compatibility matrix](https://github.com/fossas/fossa-cli/issues/55)
